Cleaned up and added some interface tests.

diff --git a/custom/cookbooks/simplerock/templates/default/rock_health_check.erb b/custom/cookbooks/simplerock/templates/default/rock_health_check.erb
--- a/custom/cookbooks/simplerock/templates/default/rock_health_check.erb
+++ b/custom/cookbooks/simplerock/templates/default/rock_health_check.erb
@@ -1,48 +1,113 @@
-#!/usr/local/bin/bats
+#!/usr/bin/bats
 
+export ZOOKEEPER_HOST=127.0.0.1
 export ZOOKEEPER_PORT=2181
+export MON_IFS=$(cat /opt/bro/etc/node.cfg | grep interface | \
+	sed 's/interface=//' | paste -sd " " -)
+
+export MYTMPDIR=$(mktemp -d)
+trap 'rm -rf "${TMPDIR}"' EXIT INT TERM HUP
+
+
+#----------------------------------------------------------------------------
+#                               INTERFACE
+#----------------------------------------------------------------------------
+
+@test "Check each monitor interface is live" {
+  local timeout_sec=5
+  local timeout_pkt=5
+  local results=()
+
+  # Timeout after 5 seconds or 5 packets
+  for interface in $MON_IFS; do
+    packets_1=$(ethtool -S ${interface} | awk '/rx_packets/ {print $2}')
+    sleep ${timeout_sec}
+    packets_2=$(ethtool -S ${interface} | awk '/rx_packets/ {print $2}') 
+    packets=$(echo `expr ${packets_2} - ${packets_1}`)
+    echo "${interface} had ${packets} packets in ${timeout_sec} secs."
+    [ $packets -gt 0 ]
+  done
+}
+
+@test "Check interface errors" {
+
+  for interface in $MON_IFS; do
+    count=$(ethtool -S ${interface} | grep error | grep -v " 0$" | wc -l )
+    echo "${interface} had ${count} error types."
+    echo ">> Check \`ethtool -S ${interface}\` << "
+    [ $count -eq 1 ]
+  done
+}
+
+#----------------------------------------------------------------------------
+#                               BRO
+#----------------------------------------------------------------------------
+
 
 @test "Check that broctl is running" {
   sudo /opt/bro/bin/broctl status
 }
+
+#----------------------------------------------------------------------------
+#                               ZOOKEEPER
+#----------------------------------------------------------------------------
 
 @test "Check that zookeeper is running" {
   service zookeeper status
 }
 
 @test "Check that zookeeper is listening" {
-  ss -lnt | grep ${ZOOKEEPER_PORT}
+  ss -lnt | grep ${ZOOKEEPER_PORT} 
 }
 
 @test "Check that client can connect to zookeeper" {
-  echo "" | ncat  127.0.0.1 ${ZOOKEEPER_PORT}
+  echo "" | ncat  ${ZOOKEEPER_HOST} ${ZOOKEEPER_PORT} 
 }
 
-@test "Check that kafka is connected to zookeeper" {
-  kafka_pid=$(systemctl show -p MainPID kafka.service | cut -d= -f2)
-  echo "kafka_pid: ${kafka_pid}"
-  kafka_socket=$(sudo ss -ntp | grep "${kafka_pid}" | grep "${ZOOKEEPER_PORT}" | awk '{ print $4 }')
-  echo "Kafka socket: ${kafka_socket}"
-  kafka_conns=$(echo "cons" | ncat 127.0.0.1 ${ZOOKEEPER_PORT} | grep "${kafka_socket}" )
-  echo -e "Kafka Connections: \n ${kafka_conns}"
-  conn_count=$(echo ${kafka_conns} | wc -l )
-  echo "Number of Kafka Conns: ${conn_count}"
-  # It's possible this might need to be -ge
-  [[ ${conn_count} -eq 1 ]]
-}
-
+#----------------------------------------------------------------------------
+#                               KAFKA
+#----------------------------------------------------------------------------
 
 @test "Check that kafka is running" {
   service kafka status
 }
 
+@test "Check that kafka is connected to zookeeper" {
+  kafka_pid=$(systemctl show -p MainPID kafka.service | cut -d= -f2) 
+  echo "kafka_pid: ${kafka_pid}"
+  kafka_socket=$(sudo ss -ntp | grep "${kafka_pid}" | \
+	grep "${ZOOKEEPER_PORT}" | awk '{ print $4 }')
+  echo "Kafka socket: ${kafka_socket}"
+  kafka_conns=$(echo "cons" | ncat ${ZOOKEEPER_HOST} ${ZOOKEEPER_PORT} | \
+	grep "${kafka_socket}" )
+  echo -e "Kafka Connections: \n ${kafka_conns}"
+  conn_count=$(echo ${kafka_conns} | wc -l )
+  echo "Number of Kafka Conns: ${conn_count}"
+  # It's possible this might need to be -ge
+  [ ${conn_count} -eq 1 ]
+}
+
+#----------------------------------------------------------------------------
+#                               LOGSTASH
+#----------------------------------------------------------------------------
+
 @test "Check that logstash is running" {
   ps -ef | grep $(cat /var/run/logstash.pid )
 }
 
+#----------------------------------------------------------------------------
+#                               ELASTICSEARCH
+#----------------------------------------------------------------------------
+
+
 @test "Check that elasticsearch is running" {
   service elasticsearch status
 }
+
+#----------------------------------------------------------------------------
+#                               KIBANA
+#----------------------------------------------------------------------------
+
 
 @test "Check that kibana is running" {
   service kibana status
